version: "3"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    
    
    volumes:
      - ./antigo:/app
      - ./antigo/custom.ini:/opt/docker/etc/php/php.ini

      
